import {
  Archive,
  BookOpen,
  Briefcase,
  CalendarDays,
  ClipboardList,
  DollarSign,
  FileText,
  GitBranch,
  HandCoins,
  Handshake,
  Inbox,
  LayoutDashboard,
  LifeBuoy,
  PackageCheck,
  Receipt,
  Repeat,
  Server,
  Settings,
  UsersRound,
  Wallet,
} from "lucide-react";
import { PERMISSIONS as P, type SidebarGroup } from "@/lib/rbac/permissions";

/**
 * The Follow-up dashboard navigation. Labels resolve from i18n (`nav.*`) with
 * the English `title` as fallback. Each item's `permission` mirrors the API
 * route guards; `filterSidebarConfig` prunes what the user can't reach.
 */
export const NAV_GROUPS: SidebarGroup[] = [
  {
    id: "main",
    items: [
      {
        id: "dashboard",
        title: "Dashboard",
        i18nKey: "nav.dashboard",
        icon: LayoutDashboard,
        href: "/dashboard",
      },
      {
        id: "pipeline",
        title: "Sales Pipeline",
        i18nKey: "nav.pipeline",
        icon: GitBranch,
        href: "/dashboard/pipeline",
        permission: P.VIEW_PIPELINE,
      },
      {
        id: "website-requests",
        title: "Website requests",
        i18nKey: "nav.website_requests",
        icon: Inbox,
        href: "/dashboard/website-requests",
        permission: P.VIEW_WEBSITE_REQUESTS,
      },
      {
        id: "projects",
        title: "Delivery",
        i18nKey: "nav.projects",
        icon: PackageCheck,
        href: "/dashboard/projects",
        permission: P.VIEW_PROJECTS,
      },
      {
        id: "servers",
        title: "Servers",
        i18nKey: "nav.servers",
        icon: Server,
        href: "/dashboard/servers",
        permission: P.VIEW_SERVERS,
      },
      {
        id: "reports",
        title: "Reports",
        i18nKey: "nav.reports",
        icon: ClipboardList,
        href: "/dashboard/reports",
        permission: P.VIEW_REPORTS,
      },
      {
        id: "support",
        title: "Support",
        i18nKey: "nav.support",
        icon: LifeBuoy,
        href: "/dashboard/support",
        permission: P.VIEW_SUPPORT,
      },
      {
        id: "leaves",
        title: "Leaves",
        i18nKey: "nav.leaves",
        icon: CalendarDays,
        href: "/dashboard/leaves",
        permission: P.VIEW_LEAVES,
      },
      {
        id: "finance",
        title: "Finance",
        i18nKey: "nav.finance",
        icon: DollarSign,
        href: "/dashboard/finance",
        permission: P.VIEW_FINANCE,
        children: [
          {
            id: "finance-ledger",
            title: "Ledger",
            i18nKey: "nav.finance_ledger",
            icon: BookOpen,
            href: "/dashboard/finance?tab=ledger",
          },
          {
            id: "finance-requests",
            title: "Spend Requests",
            i18nKey: "nav.finance_requests",
            icon: HandCoins,
            href: "/dashboard/finance?tab=requests",
          },
          {
            id: "finance-payroll",
            title: "Payroll",
            i18nKey: "nav.finance_payroll",
            icon: Wallet,
            href: "/dashboard/finance?tab=payroll",
          },
          {
            id: "finance-subs",
            title: "Subscriptions",
            i18nKey: "nav.finance_subs",
            icon: Repeat,
            href: "/dashboard/finance?tab=subs",
          },
          {
            id: "finance-invoices",
            title: "Invoices",
            i18nKey: "nav.finance_invoices",
            icon: Receipt,
            href: "/dashboard/finance?tab=invoices",
          },
          {
            id: "finance-archive",
            title: "Monthly Archive",
            i18nKey: "nav.finance_archive",
            icon: Archive,
            href: "/dashboard/finance?tab=archive",
          },
        ],
      },
      {
        id: "partners",
        title: "Partners",
        i18nKey: "nav.partners",
        icon: Handshake,
        href: "/dashboard/partners",
        permission: P.VIEW_PARTNERS,
      },
      {
        id: "careers",
        title: "Careers",
        i18nKey: "nav.careers",
        icon: Briefcase,
        href: "/dashboard/careers",
        permission: P.VIEW_CAREERS,
      },
      {
        id: "users",
        title: "Users",
        i18nKey: "nav.users",
        icon: UsersRound,
        href: "/dashboard/users",
        permission: P.MANAGE_USERS,
      },
      {
        id: "settings",
        title: "Settings",
        i18nKey: "nav.settings",
        icon: Settings,
        href: "/dashboard/settings",
        permission: P.MANAGE_SETTINGS,
      },
    ],
  },
];
