/**
 * A 512x256 equirectangular LAND/OCEAN bitmask, one bit per cell, MSB first.
 *
 * ── Why a bitmask and not GeoJSON ─────────────────────────────────────────
 * The hero globe needs one question answered a few thousand times per layout:
 * "is this lat/lon on land?" Point-in-polygon against 127 rings is the wrong
 * shape for that — it is a per-point loop over coastline geometry, on the main
 * thread, every resize. A prebaked raster answers it with two shifts and a mask.
 * It is also ~16KB packed against ~138KB of source polygons, and it needs no
 * runtime dependency to parse.
 *
 * ── Provenance ────────────────────────────────────────────────────────────
 * Rasterised from Natural Earth `ne_110m_land` (1:110m physical land polygons),
 * which is in the PUBLIC DOMAIN — https://www.naturalearthdata.com/about/terms-of-use/.
 * 127 polygons filled with the even-odd rule so lakes and inland seas read as
 * ocean. Verified against a rendered preview: recognisable continents, correct
 * orientation, land fraction 33.2% (Earth is ~29%; equirectangular inflates the
 * poles, and Antarctica is included).
 *
 * ⚠️ Row 0 is +90 degrees latitude (NORTH) and column 0 is -180 longitude. Get
 * either flipped and the globe renders a plausible-looking world that is wrong,
 * which is far harder to notice than a broken one.
 */
export const LAND_MASK_W = 512;
export const LAND_MASK_H = 256;

const LAND_MASK_B64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AP//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABP////gAAA/////+AAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////B////////jAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMP////+H///////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////4f///////////gAAAAAAAHMAAAAA/AAAAAAAAAB/wAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAH/9///4D///////////AAAAAAAY//8AAAAAAAAAAAAAAAP/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgA" +
  "H/H/8AH///////////gAAAAAAP/4AAAAAAAAAAAAAAAAAfzgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAPzw/P//D/////////" +
  "///wAAAAAAA/4AAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAACAH/+AH///////////8AAAAAAAD4OA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAADwH//AA////////////AAAAAAAAMAAAAAAAAAAAAAAAAA" +
  "AAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+HBwB+D4ADAAD///////////gAAAAAAAAAAAAAAAAAAH/gAAAAAAP//+AAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAH/vwfgP4/gAAAAP////////8AAAAAAAAAAAAAAAAAA/wAAAAAD/////wAAAAB/8AAAAAAAAAAAAAAAA" +
  "AAAAAAAB8AABx//8AAAAA////////+AAAAAAAAAAAAAAAAAB/AAAAAAf/////gAAAAAP+DgAAAAAAAAAAAAAAAAAAAH/AAAAADAA" +
  "AAAAAAH////////gAAAAAAAAAAAAAAAAB+AAAAAAH/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/+AA4Pz8OHfAAAAA////////" +
  "wAAAAAAAAAAAAAAAAAeAAAAAH////////4H4AADwAAAAAAAAAAAAAAAAAAAAA/7/k8H88P/4YAAAAD///////wAAAAAAAAAAAAAA" +
  "AAAfAAAeAB///////////gAAAAAAAAAAAAAAAAAAAAAAAAf5//3g/sD///gAAAB///////4AAAAAAAAAAAAAAAAAPgAAPiff////" +
  "//////4AA//4AAAAAADAAAAAAAAAAAAA8H//4Bnw////wAAAD///////gAAAAAAAAAAAAAAAAB8AAP7/////////////H////gAA" +
  "AAABAAAAD/8AAAAAAAD///gB+H////AAAB//////84AAAAAAAAAAP+AAAAAAAAH+f///////////////////4AAAAAAAAH////gA" +
  "B3AAP///CfgD/v//AAA///////4AAAAAAAAAD//gAAAAAAAB/n///////////////////+AAOAAAAAH/////4f///j///h5+A/Af" +
  "/wAAAf/////wAAAAAAAAAD///wAAAAAD8H5//////////////////////z/+wAAf///////////5g8AAP+PwB/4AAAP/////AAAA" +
  "AAAAAAH////8AAA4M/4/P/////////////////////////gAB///////////+DP8Pv/n8Dj/8AAP////wAAAAAAAAAAH/////4HD" +
  "/////z/////////////////////////+AAH///////////////////AQ//gAD////wAAAAAAAAAAD//////Bj/////5/////////" +
  "//////////////////gGf/////////////////2AAf//AA////4AAABgAAAAAB////8fif/////8////////////////////////" +
  "/7/8P//////////////////4AAH+HgAP//+AAAP/4AAAAAB//x//gH////////////////////////////////8D4B//////////" +
  "////////94B//4AAA//+AAAA//AAAAAA//wP/8x/////////////////////////////////AEAAH////////////////+fwef/g" +
  "AAP//AAAAP/gAAAAAf/8P//H////////////////////////////////+AAAAB////////////////4HGAB/8AAB//wAAAAOAAAA" +
  "AAf/8P////////////////////////////////////wAAAP////////////////+ACAAHzAAAP/wAAAAAAAAAAA//8P/////////" +
  "///////////////////////////+AAAH////////////////8ABCfwGAAAB/4AAAAAAAAAAA//+D////////////////////////" +
  "/////////z//4AAAD////////////////+AAAH/AAAAAP+AAAAAAAAAAAf//gf///////////////////////////////55//AAA" +
  "AAf////////////////AAAB/+AAAAA/gAAAAAAAAAAH//4H///////////////////////////////wY//AAAAAT//74P///////" +
  "////gAAAP/gAAAAAQAAAAAAAAAAB///A4H/////////////////////////////wA/wAAAAAAD/4wAA//////////4AAAH/4GAAA" +
  "AAAAAAAAAAAAAP//wB/////////////////////////////x8A8AAAAAAAAH/AAAD//////////gAAB//jwAAAAAAAAAAAAAAAD4" +
  "/wB///////////////////////////+AAAAeAAAAAAAAAPAAAAB/////////8AAAP//+AAAAAAAAAAAAAOAAAP8AH///////////" +
  "////////////////AAAAfgAAAAAAAAHOAAAAP/////////gAAB///wAAAAAAAAAAAAD4AAJ+Ab//////////////////////////" +
  "/AAAAf8AAAAAAAAHAAAAAB//////////wAAf//8AAAAAAAAAAAAA8AAOPgP///////////////////////////AAAAP/AAAAAAAA" +
  "PAAAAAAP//////////gAP///wAAAAAAAAAAAAPgADHgD///////////////////////////gAAAH/gAAAAAAAMAAAAAAB///////" +
  "////wH///+AAAAAAAAAAAAB8AAzAA///////////////////////////gAAAB/wAAAAAAAIAAAAAAAP//////////+H////+AAAA" +
  "AAAAAAAPHgAOAf///////////////////////////+AAAAf4AAAAAAAAAAAAAAAQ///////////g/////gAAAAAAAAAAPg8AD///" +
  "////////////////////////////IAAD8AAAAAAAAAAAAAAAEP//////////4P////+AAAAAAAAAAB5/gf//////////////////" +
  "/////////////7AAA+AAAAAAAAAAAAAAAAA///////////D/////gAAAAAAAAAA+P8P////////////////////////////////w" +
  "AAOAAAAAAAAAAAAAAAAAP//////////4/////gAAAAAAAAAAAH/H////////////////////////////////sAADgAAAAAAAAAAA" +
  "AAAAAB////////////////GAAAAAAAAAAAA/n////////////////////////////////zAAAAAAAAAAAAAAAAAAAAA/////////" +
  "///////DAAAAAAAAAAAAwD////////////////////////////////84AAAAAAAAAAAAAAAAAAAADf////////////8GB4AAAAAA" +
  "AAAAAAH/////////////////////////////////OAAAAAAAAAAAAAAAAAAAAAd////////////88AfwAAAAAAAAAAAH////////" +
  "/////////////////////////iAAAAAAAAAAAAAAAAAAAAABP///////////+/AP+AAAAAAAAAAAP///////////////////////" +
  "//////////4gAAAAAAAAAAAAAAAAAAAAAb////////////fwAFgAAAAAAAAAAA/////////////////////////////////8IAAA" +
  "AAAAAAAAAAAAAAAAAAD/////////////8AAYAAAAAAAAAAAH////////8///H///////////////////+DAAAAAAAAAAAAAAAAAA" +
  "AAAA//////////////hAAAAAAAAAAAAAA///////4cP/+A////////////////////AAAAAAAAAAAAAAAAAAAAAAAP//////////" +
  "////gAAAAAAAAAAAAAP//9///8Hn/+Af///////////////////gAAAAAAAAAAAAAAAAAAAAAAD/////////////PAAAAAAAAAAA" +
  "AAAD///H//+Ah//gf///////////////////wGAAAAAAAAAAAAAAAAAAAAAB/////////////DAAAAAAAAAAAAAAA//jw///gAD/" +
  "4P///////////////////4B+AAAAAAAAAAAAAAAAAAAAAf////////////AAAAAAAAAAAAAAH//4wfD//wAAf/B/////////////" +
  "//////4A/gAAAAAAAAAAAAAAAAAAAAH////////////gAAAAAAAAAAAAAB//8AjwP/4AAB/wH//////////////////AAbAAAAAA" +
  "AAAAAAAAAAAAAAAB////////////8AAAAAAAAAAAAAAf//AIfh//AeAf+Af/////////////////gAGAAAAAAAAAAAAAAAAAAAAA" +
  "Af///////////4AAAAAAAAAAAAAAH//AAB8P/7/8P/wH/////////////////wAAgAAAAAAAAAAAAAAAAAAAAAH///////////4A" +
  "AAAAAAAAAAAAAB//gAwHz8f////+H///////////////5/4AAcAAAAAAAAAAAAAAAAAAAAAA///////////8AAAAAAAAAAAAAAAf" +
  "/wAMAw+D/////A///////////////8d8AAHAAAAAAAAAAAAAAAAAAAAAAP//////////+AAAAAAAAAAAAAAAP/8ACAEHg/////wP" +
  "//////////////8APAABwAAAAAAAAAAAAAAAAAAAAAB///////////gAAAAAAAAAAAAAAB/+AAACA8P////8D///////////////" +
  "AD4AA4AAAAAAAAAAAAAAAAAAAAAAP//////////wAAAAAAAAAAAAAAAP/gAAPAOD/////Af//////////////5APAAcAAAAAAAAA" +
  "AAAAAAAAAAAAAD//////////8AAAAAAAAAAAAAAAA/gA/gwBgf////+P///////////////8DwA/AAAAAAAAAAAAAAAAAAAAAAAf" +
  "//////////AAAAAAAAAAAAAAAAGA//4AAAADH///////////////////8A8APwAAAAAAAAAAAAAAAAAAAAAAD//////////wAAAA" +
  "AAAAAAAAAAAAg//+AAAAAB///////////////////8APB/8AAAAAAAAAAAAAAAAAAAAAAA//////////4AAAAAAAAAAAAAAAAf//" +
  "/gAAAAMf///////////////////ADB/8AAAAAAAAAAAAAAAAAAAAAAAB/////////4AAAAAAAAAAAAAAAAP///4AAAAAH///////" +
  "////////////4AA6wAAAAAAAAAAAAAAAAAAAAAAAAH////////4AAAAAAAAAAAAAAAAP////AAAAAD////////////////////AA" +
  "bAAAAAAAAAAAAAAAAAAAAAAAAAB////////8AAAAAAAAAAAAAAAAH/////ADAAA////////////////////wAGAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAP///////+AAAAAAAAAAAAAAAAB/////8D8AAf///////////////////+ABgAAAAAAAAAAAAAAAAAAAAAAAAADn/" +
  "//////AAAAAAAAAAAAAAAAA//////g/+GH////////////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAZ///////wAAAAAAAA" +
  "AAAAAAAAP//////P///////////////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAGP////+BcAAAAAAAAAAAAAAAAD//////" +
  "///////4////////////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAT///+AADgAAAAAAAAAAAAAAAB/////////////+P//////" +
  "//////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAACf//+AAA4AAAAAAAAAAAAAAAA//////////////h////////////////4AAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAABz///AAAPAAAAAAAAAAAAAAAA//////////+P//8P///////////////8AAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAef//wAABwAAAAAAAAAAAAAAAf//////////x///g///////////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAj//8" +
  "AAAcAAAAAAAAAAAAAAAP//////////8P//4Af//////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMf//AAADAAAAAAAAAAA" +
  "AAAAH///////////j///gT//////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAABD//gAAAAAAAAAAAAAAAAAAB//////////" +
  "/8f//4MAAf///////////4gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIf/4AAAAQAAAAAAAAAAAAAA////////////H///HgAD/////" +
  "//////8YAAAAAAAAAAAAAAAAAAAAAAAAAAAAABD/+AAAAAAAAAAAAAAAAAAAf///////////4f///+AAf//////////+GAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAf/gAAHwAAAAAAAAAAAAAAH///////////+H////wAB//////////+BAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAD/4AACPgAAAAAAAAAAAAAD////////////w////+AAf////n////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+AAw" +
  "AOAAAAAAAAAAAAAA////////////+P////AAH///8B///4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/wA8AB4AAAAAAAAAAAA" +
  "AP////////////j////gAAH///Af//8IAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAD/8AfAAPAAAAAAAAAAAAAB////////////4" +
  "f///wAAA///gD//+CAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAf/gHwAAD4AAAAAAAAAAAAf///////////+D///8AAAP//gAf/" +
  "/BgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/+H4AAAfgAAAAAAAAAAAH////////////gf//+AAAD//wAD//4YAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAH//+AAYCBAAAAAAAAAAAB////////////8H///AAAA//4AA//+AAAcAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAf//AAAAAAAAAAAAAAAAAf////////////g///AAAAP/4AAP//wAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//wAAA" +
  "AAAAAAAAAAAAAH////////////8H/+AAAAD/+AAD//+AABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH98AAAAAAAAAAAAAAAD/" +
  "////////////B//AAAAAf8AAAR//wAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAAAAAAAAAAAA/////////////4f/" +
  "gAAAAH/AAAAf/+AAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/8AAAAAAAAAAAAAAAP/////////////n/AAAAAA/wAAAH//g" +
  "AAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAAAAAAAAAAAAAAD/////////////9/AAAAAAP8AAAA//4AAPAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAA//////////////sAAAAAAD/AAAAM/+AACQAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAD4AAAAAAAAAAAAAAAP/////////////8AAAAAAAfwAAADH/gAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAMgA" +
  "AAAAAAAAAAB/////////////+AGAAAAAH8AAAAw/4AACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAfeAAAAAAAAAAAAH///" +
  "//////////w/gAAAAA/AAAAIH8AABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AH3+6AAAAAAAAAAB///////////////wAA" +
  "AAAPgAAACAcAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADhD9//gAAAAAAAAAAP//////////////8AAAAAByAAAAgGAACC" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAft///8AAAAAAAAAAB///////////////AAAAAAYgAAAMAAAAAHAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAx////wAAAAAAAAAAf//////////////gAAAAAAcAAABgAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAEf///+AAAAAAAAAAD//////////////4AAAAAAHAAAAYAAAAC8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////wA" +
  "AAAAAAAAAP/////////////8AAAAAAAwAAADAAACAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////+AAAAAAAAAAB//8H/" +
  "/////////AAAAAAAAAAAAcAABwBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////gAAAAAAAAAP/4B//////////gAAAAA" +
  "AAAAAMHgAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////8AAAAAAAAAAwAAO/////////wAAAAAAAAAADh4AA/AAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////gAAAAAAAAAAAAAH////////4AAAAAAAAAAAceAAPgAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAP/////8AAAAAAAAAAAAAA////////+AAAAAAAAAAADzgAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAP//////AAAAAAAAAAAAAAP////////AAAAAAAAAAAAecAP/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////4AA" +
  "AAAAAAAAAAAH////////AAAAAAAAAAAAD7AD/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//////+AAAAAAAAAAAAAB///" +
  "/////gAAAAAAAAAAAAfAH/+IRgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////AAAAAAAAAAAAAAf///////gAAAAAAAAA" +
  "AAAH4B/+H4YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////+AAAAAAAAAAAAAH///////wAAAAAAAAAAAAA+Af/iAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///////8AAAAAAAAAAAAB///////8AAAAAAAAAAAAAHwD/4mAD4AAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAB////////wAAAAAAAAAAAAf//////+AAAAAAAAAAAAAB+Af8OAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAf///////+AAAAAAAAAAAAD///////AAAAAAAAAAAAAAPwH/HgADj4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////wAA" +
  "AAAAAAAAAf//////gAAAAAAAAAAAAAB+AfhsA49/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//////////AAAAAAAAAAAD/////" +
  "/4AAAAAAAAAAAAAAfgAQLAAF//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////4AAAAAAAAAAA//////8AAAAAAAAAAAAA" +
  "AB4AACYAAH/+AIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////////wAAAAAAAAAAH/////+AAAAAAAAAAAAAAAOAAAiAAAP/wEA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAB//////////8AAAAAAAAAAB//////gAAAAAAAAAAAAAAAQAAAAABB/+OCAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAP//////////AAAAAAAAAAAP/////8AAAAAAAAAAAAAAAPEAAAAAAf/wAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAB" +
  "//////////4AAAAAAAAAAD//////AAAAAAAAAAAAAAAA/4AAAAAH/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////////8AAAA" +
  "AAAAAAAf/////wAAAAAAAAAAAAAAAAfwAAAAD/DgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////AAAAAAAAAAAH/////8A" +
  "AAAAAAAAAAAAAAAAA5gwAADw4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////gAAAAAAAAAAD//////AAAAAAAAAAAAAAAA" +
  "AAAgwAAAAHgAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////4AAAAAAAAAAAf/////4AAAAAAAAAAAAAAAAAAAIAAAAAcAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAB/////////8AAAAAAAAAAAH//////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAP////////+AAAAAAAAAAAB//////wAAAAAAAAAAAAAAAAAAAAAwAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//" +
  "///////AAAAAAAAAAAAf/////8AAAAAAAAAAAAAAAAAAAAA/4DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////////gAAAAAAA" +
  "AAAAP//////ABgAAAAAAAAAAAAAAAAAAf8AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////4AAAAAAAAAAAD//////wAYA" +
  "AAAAAAAAAAAAAAAAAH+AcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////+AAAAAAAAAAAB//////8AOAAAAAAAAAAAAAAAA" +
  "ABz/gHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////gAAAAAAAAAAAf//////AHwAAAAAAAAAAAAAAAAA//4B+AAAABAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAA////////4AAAAAAAAAAAH//////gD4AAAAAAAAAAAAAAAAAf//gfgAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAD///////8AAAAAAAAAAAB//////wH+AAAAAAAAAAAAAAAAAP//8H4AAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAP///" +
  "////AAAAAAAAAAAAf/////wB/AAAAAAAAAAAAAAAAAP///z/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///////wAAAAAAAAAA" +
  "AH/////4AfwAAAAAAAAAAAAAAAAD/////wAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAP//////8AAAAAAAAAAAB/////8AH8AAAA" +
  "AAAAAAAAAAAAB/////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////+AAAAAAAAAAAAP////8AB/AAAAAAAAAAAAAAAAA//" +
  "////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////gAAAAAAAAAAAD////+AAfgAAAAAAAAAAAAAAAA//////+AAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAP//////wAAAAAAAAAAAAf////wAH4AAAAAAAAAAAAAAAD///////wAAAgAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAD//////8AAAAAAAAAAAAD////8AD+AAAAAAAAAAAAAAAD///////8AAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////" +
  "+AAAAAAAAAAAAA/////AA/AAAAAAAAAAAAAAAD////////gAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////AAAAAAAAAAAAAP" +
  "////4APwAAAAAAAAAAAAAAA////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////8AAAAAAAAAAAAAD////8AD8AAAAAAA" +
  "AAAAAAAAP////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////8AAAAAAAAAAAAAAf////AA+AAAAAAAAAAAAAAAH//////" +
  "//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAH////AAHgAAAAAAAAAAAAAAA/////////gAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAH////+AAAAAAAAAAAAAAB////AAAAAAAAAAAAAAAAAAAP////////8AAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAB/////gAAAAAAAAAAAAAAf///4AAAAAAAAAAAAAAAAAAD/////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////4AAA" +
  "AAAAAAAAAAAD///+AAAAAAAAAAAAAAAAAAA/////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////+AAAAAAAAAAAAAAA///" +
  "/AAAAAAAAAAAAAAAAAAAP////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////gAAAAAAAAAAAAAAH///wAAAAAAAAAAAAA" +
  "AAAAAB/////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAA///4AAAAAAAAAAAAAAAAAAAf////////" +
  "wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////4AAAAAAAAAAAAAAAP//8AAAAAAAAAAAAAAAAAAAD////////8AAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAD////8AAAAAAAAAAAAAAAB//+AAAAAAAAAAAAAAAAAAAA/////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAA////+AAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAP////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////AAAAAAA" +
  "AAAAAAAAAD//gAAAAAAAAAAAAAAAAAAAB//8B////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////gAAAAAAAAAAAAAAAA//wAA" +
  "AAAAAAAAAAAAAAAAAAf/wAH///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////4AAAAAAAAAAAAAAAAP/wAAAAAAAAAAAAAAAAA" +
  "AAAP/wAA7//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///8AAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAD8AAAM///gAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAX//4AAAACAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAB///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//8AAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "///+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAP///gAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//gAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAH///wAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAf/4AAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAB///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAA7gAAAAAD8AAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "+AAAAAAAAAAAAAAAAAAAAAAAAAH//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAf/w" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAEQAAAAAAAAAAAAAAAAAAAAAAAAAH/8AAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAB//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAABwAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAP/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAYAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAD/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAD/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAA/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAH/4AAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAB/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/AAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/wAOAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "BgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAB/" +
  "gAAAAAAEAAD8A/AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAD/+AAAAAAf/4D////" +
  "j/////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAf//+P8AAH///////////////gAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAD//////gAP////////////////wAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAA5/AAAAAAAAAAAAAAAAAAAAAAB+H//////4AH//////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPf4A" +
  "AAAAAAAAAAAAAAAAGfgAH////////8B////////////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD3/AAAAAAAAAAAAAAAB" +
  "/n/////////////A/////////////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAP+/4AAAAAAAAAAAGMOf///////////////" +
  "g///////////////////////wAAAAAAAAAAAAAAAAAAAAfwAAAAD/P+AAAAAAAAAAAD//////////////////4f/////////////" +
  "/////////+AAAAAAAAAAAAAAAAAAAAeAAEAAAAH/gAAAAAAAAAAH///////////////////////////////////////////AAAAA" +
  "AAAAAAAAAAAwAAAH+H//B4D//8AAAAAAAAAAf///////////////////////////////////////////gAAAAAAAAAAAAAAAAf4A" +
  "Af////////+AAAAAAAAAAD///////////////////////////////////////////AAAAAAAAAAAAB//////+AB////////4AAAA" +
  "AAAAAAD//////////////////////////////////////////+AAAAAAAAAAAP//////////////////wAAAAAAAAAAP////////" +
  "//////////////////////////////////+AAAAAAAAAAAD/////////////////+AAAAAAAAAAf////////////////////////" +
  "////////////////////gAAAAAAAAAAP////////////////4AAAAAAAAAAD////////////////////////////////////////" +
  "/////4AAAAAAAAH///////////////////4AAAAAAAAAP/////////////////////////////////////////////+AAAAAAADg" +
  "//////////////////+AAAAAAD+AB///////////////////////////////////////////////+AAAAAAAeB//////////////" +
  "////gAAAAAD/wAf//////////////////////////////////////////////4AAAAAAAAAAA////////////////+AAAGAB/8AA" +
  "A/////////////////////////////////////////////gAAAAAAAAAAAH/////////////////gB/gH/wAAAf/////////////" +
  "///////////////////////////////wAAAAAAAAAA+f//////////////////wAAAAAAB//////////////////////////////" +
  "////////////////+AAAAAAAAAAH/////////////////////gAA/w//////////////////////////////////////////////" +
  "//wAAAAAAAAAAf/////////////////////wf///////////////////////////////////////////////////wAAAAAAAAAP/" +
  "//////////////////////////////////////////////////////////////////////////8AAAA+AAAAP///////////////" +
  "////////////////////////////////////////////////////////////+AD///AAAAAP////////////////////////////" +
  "///////////////////////////////////////////////////////h////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "/////////////////////////////////////////////w==";

/** Lazily unpacked on first use — decoding 16KB at module load costs every page. */
let bytes: Uint8Array | null = null;

function maskBytes(): Uint8Array {
  if (bytes) return bytes;
  const bin = atob(LAND_MASK_B64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  bytes = out;
  return out;
}

/**
 * Is this coordinate on land? `lon` in [-180, 180], `lat` in [-90, 90].
 *
 * Out-of-range latitudes clamp rather than wrap: a point at 91 degrees is a
 * caller bug, and wrapping it to the far side of the pole would silently paint
 * land in the wrong hemisphere.
 */
export function isLand(lon: number, lat: number): boolean {
  const m = maskBytes();
  let x = Math.floor(((lon + 180) / 360) * LAND_MASK_W);
  let y = Math.floor(((90 - lat) / 180) * LAND_MASK_H);
  x = ((x % LAND_MASK_W) + LAND_MASK_W) % LAND_MASK_W;
  y = y < 0 ? 0 : y >= LAND_MASK_H ? LAND_MASK_H - 1 : y;
  const i = y * LAND_MASK_W + x;
  return (m[i >> 3] & (0x80 >> (i & 7))) !== 0;
}
