import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { getMessages, setRequestLocale } from "next-intl/server";
import { getDir } from "@/lib/utils";
import { NextIntlClientProvider } from "next-intl";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import LenisProvider from "@/providers/ lenis-provider";
import localFont from "next/font/local";
import { Dialog, DialogTitle } from "@/components/ui/dialog";
import { ContactUsDialog } from "@/components/ContactUsDialog";

export const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-urbanist",
});

const dahabArabic = localFont({
  src: [
    {
      path: "./fonts/Dahab Arabic ITF Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/Dahab Arabic ITF Extra Bold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/Dahab Arabic ITF Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Dahab Arabic ITF Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Dahab Arabic ITF Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Dahab Arabic ITF Light.otf",
      weight: "300",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  setRequestLocale(locale);

  const messages = await getMessages();
  const dir = getDir(locale);
  return (
    <html lang={locale} dir={dir} suppressHydrationWarning>
      <body
        className={`antialiased ${locale == "en" && urbanist.className} ${locale == "ar" && dahabArabic.className}`}
        suppressHydrationWarning
      >
        <NextIntlClientProvider messages={messages}>
          <LenisProvider>
            <Header />
            {children}
            <ContactUsDialog />
            <Footer />
          </LenisProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
